Repository yurak/fanta, pull requests merged in 2020-03, with the labels that each got.

#110 Redesign part2
  .rubocop.yml
  .rubocop_todo.yml
  .travis.yml
  app/assets/images/modules-long.jpg
  app/assets/images/modules-long.png
  app/assets/images/modules.jpg
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/articles.scss
  app/assets/stylesheets/clubs.scss
  app/assets/stylesheets/lineups.scss
  app/assets/stylesheets/links.scss
  app/assets/stylesheets/list-template.scss
  app/assets/stylesheets/teams.scss
  app/assets/stylesheets/tours.scss
  app/controllers/api/results_controller.rb
  app/controllers/clubs_controller.rb
  app/controllers/links_controller.rb
  app/controllers/players_controller.rb
  app/controllers/teams_controller.rb
  app/controllers/tours_controller.rb
  app/models/league.rb
  app/models/match_player.rb
  app/models/position.rb
  app/models/result.rb
  app/models/team.rb
  app/services/calendar_creator.rb
  app/services/results_manager.rb
  app/services/seeder.rb
  app/services/slot_creator.rb
  app/services/team_lineups/creator.rb
  app/services/telegram/sender.rb
  app/services/tour_manager.rb
  app/services/user_creator.rb
  app/views/articles/index.html.haml
  app/views/clubs/index.html.haml
  app/views/layouts/_navbar_links.html.haml
  app/views/lineups/_card.html.haml
  app/views/lineups/_edit_form.html.haml
  app/views/lineups/_match_player_scores.html.haml
  app/views/lineups/details.html.haml
  app/views/lineups/edit.html.haml
  app/views/lineups/edit_module.html.haml
  app/views/lineups/edit_scores.html.haml
  app/views/lineups/new.html.haml
  app/views/lineups/show.html.haml
  app/views/lineups/substitutions.html.haml
  app/views/links/_form.html.haml
  app/views/links/edit.html.haml
  app/views/links/index.html.haml
  app/views/links/new.html.haml
  app/views/teams/index.html.haml
  app/views/tours/_fixtures.html.haml
  app/views/tours/_results.html.haml
  app/views/tours/_tour_match.html.haml
  app/views/tours/_tours_list.html.haml
  app/views/tours/edit.html.haml
  app/views/tours/index.html.haml
  app/views/tours/show.html.haml
  config/routes.rb
Labels: size/XL

#114 Leagues feature remove seeder
  app/services/seeder.rb
  db/seeds.rb
  spec/services/seeder_spec.rb
Labels: size/M

#115 Leagues injector
  Gemfile
  Gemfile.lock
  app/controllers/tours_controller.rb
  app/services/scores/injectors/calcio.rb
  app/services/scores/injectors/epl.rb
  app/services/scores/injectors/fake.rb
  app/services/scores/injectors/strategy.rb
  app/services/scores/parser.rb
  lib/tasks/db_updater.rake
  spec/factories/league.rb
  spec/factories/team.rb
  spec/factories/tour.rb
  spec/factories/tournament.rb
  spec/factories/user.rb
  spec/services/scores/injectors/strategy_spec.rb
Labels: size/L

#116 Update Model relations
  app/assets/stylesheets/players.scss
  app/controllers/leagues_controller.rb
  app/controllers/lineups_controller.rb
  app/controllers/players_controller.rb
  app/controllers/teams_controller.rb
  app/helpers/application_helper.rb
  app/models/lineup.rb
  app/models/player.rb
  app/models/player_position.rb
  app/models/player_team.rb
  app/models/position.rb
  app/models/slot.rb
  app/models/team.rb
  app/models/team_module.rb
  app/models/user.rb
  app/services/slot_creator.rb
  app/views/layouts/_navbar_links.html.haml
  app/views/lineups/details.html.haml
  app/views/lineups/show.html.haml
  app/views/players/show.html.haml
  app/views/tours/show.html.haml
  config/routes.rb
  db/migrate/20200311103807_add_id_to_players_positions.rb
  db/migrate/20200311130109_create_player_teams.rb
  db/migrate/20200311131926_migrate_db_players_team.rb
  db/migrate/20200311132807_add_player_columns.rb
  db/schema.rb
  db/seeds.rb
Labels: size/L

#119 Update UI, add ClubManager service
  app/assets/stylesheets/leagues.scss
  app/assets/stylesheets/list-template.scss
  app/assets/stylesheets/results.scss
  app/assets/stylesheets/tours.scss
  app/models/club.rb
  app/models/league.rb
  app/models/lineup.rb
  app/models/link.rb
  app/models/player.rb
  app/models/position.rb
  app/models/result.rb
  app/models/team.rb
  app/models/team_module.rb
  app/models/tour.rb
  app/models/tournament.rb
  app/services/club_manager.rb
  config/mantra/clubs.yml
  lib/tasks/clubs.rake
  lib/tasks/db_updater.rake
Labels: size/L
