Repository yurak/fanta, pull requests merged in 2021-08, with the labels that each got.

#240 Update lineup form for Mantra tours, update positions matrix
  app/assets/stylesheets/lineups.scss
  app/helpers/players_helper.rb
  app/models/lineup.rb
  app/models/position.rb
  app/views/lineups/_lineup_form.html.haml
  app/views/lineups/_lineup_player_item.html.haml
  app/views/matches/_team_squad.html.haml
  app/views/matches/show.html.haml
  app/views/teams/_mantra_team.html.haml
  app/views/tours/_round_matches.html.haml
  app/views/users/show.html.haml
  config/locales/en.yml
  config/locales/ua.yml
  lib/tasks/leagues.rake
  public/javascripts/lib/new_lineup.js.erb
  spec/factories/team.rb
  spec/helpers/players_helper_spec.rb
  spec/models/lineup_spec.rb
  spec/models/match_player_spec.rb
  spec/models/slot_spec.rb
Labels: size/XL

#241 Add params to Tournament, update Auction timer
  Gemfile.lock
  app/models/lineup.rb
  app/views/transfers/auction.html.haml
  db/migrate/20210801111230_add_fields_to_tournaments.rb
  db/schema.rb
  spec/factories/lineup.rb
  spec/factories/match.rb
  spec/models/lineup_spec.rb
  spec/models/match_spec.rb
  spec/services/results/updater_spec.rb
Labels: size/L

#242 Update transfers index page
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/players.scss
  app/assets/stylesheets/transfers.scss
  app/controllers/transfers_controller.rb
  app/views/players/index.html.haml
  app/views/transfers/index.html.haml
  config/locales/en.yml
  config/locales/ua.yml
Labels: size/L

#243 Update Auction page UI
  app/assets/stylesheets/transfers.scss
  app/helpers/players_helper.rb
  app/views/transfers/_player_row.html.haml
  app/views/transfers/auction.html.haml
  config/locales/en.yml
  config/locales/ua.yml
  spec/helpers/players_helper_spec.rb
Labels: size/XXL

#244 Add transfers to team page
  app/assets/stylesheets/teams.scss
  app/assets/stylesheets/transfers.scss
  app/views/teams/_mantra_team.html.haml
  app/views/transfers/auction.html.haml
  config/locales/en.yml
  config/locales/ua.yml
Labels: size/M

#246 Fix safari
  app/models/player.rb
  app/views/matches/_main_player.html.haml
  app/views/matches/_out_of_squad.html.haml
  app/views/matches/_subs_player.html.haml
Labels: size/S

#245 Update module image, hide guide
  app/assets/images/icons/incoming.png
  app/assets/images/icons/outgoing.png
  app/assets/images/modules/4-2-3-1.jpg
  app/assets/stylesheets/lineups.scss
  app/assets/stylesheets/teams.scss
  app/assets/stylesheets/tournament_rounds.scss
  app/assets/stylesheets/tours.scss
  app/controllers/tournament_rounds_controller.rb
  app/controllers/welcome_controller.rb
  app/helpers/players_helper.rb
  app/services/scores/injectors/fotmob_match.rb
  app/views/lineups/_lineup_form.html.haml
  app/views/teams/_mantra_team.html.haml
  app/views/tournament_rounds/edit.html.haml
  app/views/transfers/auction.html.haml
  app/views/welcome/guide.html.haml
  app/views/welcome/rules/_results.html.haml
  config/locales/en.yml
  config/locales/ua.yml
  db/migrate/20210815094206_add_fields_to_round_players.rb
  db/schema.rb
  spec/helpers/players_helper_spec.rb
Labels: size/L

#248 Open api
  app/controllers/teams_controller.rb
Labels: size/XS

#249 Add search to Players page, small fixes
  app/assets/stylesheets/players.scss
  app/assets/stylesheets/round_players.scss
  app/assets/stylesheets/teams.scss
  app/assets/stylesheets/transfers.scss
  app/controllers/players_controller.rb
  app/models/team.rb
  app/views/players/index.html.haml
  app/views/round_players/index.html.haml
  app/views/teams/_mantra_team.html.haml
  app/views/transfers/auction.html.haml
  config/locales/en.yml
  config/locales/ua.yml
  spec/models/team_spec.rb
  spec/requests/teams_spec.rb
Labels: size/L

#250 Add Cancel Transfer action
  app/assets/stylesheets/transfers.scss
  app/controllers/transfers_controller.rb
  app/models/ability.rb
  app/views/transfers/auction.html.haml
  config/routes.rb
  spec/requests/transfers_spec.rb
  spec/support/auth_helper.rb
Labels: size/L

#255 Update Lineups UI
  app/assets/stylesheets/lineups.scss
  app/assets/stylesheets/matches.scss
  app/models/club.rb
  app/serializers/player_serializer.rb
  app/views/lineups/_lineup_form.html.haml
  app/views/lineups/_lineup_player_item.html.haml
  app/views/matches/_main_player.html.haml
  app/views/matches/_out_of_squad.html.haml
  app/views/matches/_real-match.html.haml
  app/views/matches/_subs_player.html.haml
  app/views/transfers/auction.html.haml
  config/locales/en.yml
  config/locales/ua.yml
  public/javascripts/lib/new_lineup.js.erb
  spec/models/club_spec.rb
Labels: size/L
