Repository yurak/fanta, pull requests merged in 2024-03, with the labels that each got.

#427 Add notifiers for finished auction and sold player
  app/client/locales/locales.json
  app/controllers/api/players_controller.rb
  app/services/auctions/manager.rb
  app/services/players/transfermarkt/position_parser.rb
  app/services/telegram_bot/auction_finished_notifier.rb
  app/services/telegram_bot/player_sold_notifier.rb
  app/services/transfers/seller.rb
  lib/tasks/tm/check_club_player_position.rake
  spec/requests/api/players_spec.rb
  spec/services/telegram_bot/auction_finished_notifier_spec.rb
  spec/services/telegram_bot/player_sold_notifier_spec.rb
Labels: size/L

#428 Update injector
  app/services/scores/injectors/fotmob_match.rb
  spec/services/scores/injectors/fotmob_match_spec.rb
  spec/vcr/fotmob_match_finished.yml
Labels: size/M

#429 move staging to https, update position mapper
  app/client/locales/locales.json
  app/models/position.rb
  app/services/players/transfermarkt/position_mapper.rb
  app/services/players/transfermarkt/position_parser.rb
  app/services/stats/creator.rb
  app/views/players/_performance.html.haml
  app/views/players/_season_stats.html.haml
  config/environments/staging.rb
  config/locales/en.yml
  config/locales/ua.yml
  lib/tasks/tm/check_club_player_position.rake
  spec/swagger_helper.rb
  swagger/v1/swagger.yaml
Labels: size/L

#432 Update player scores
  .rubocop_todo.yml
  app/models/player.rb
  app/views/players/show.html.haml
Labels: size/S

#431 Botv2
  README.md
  app/assets/images/mantra_logo.jpeg
  app/client/locales/locales.json
  app/controllers/telegram/webhook_controller.rb
  app/services/telegram_bot/sender.rb
  app/views/devise/registrations/new.html.haml
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/staging.rb
  config/locales/en.yml
  config/locales/ua.yml
  config/routes.rb
  config/secrets.yml
  public/rules_en.pdf
  public/rules_extended_ua.pdf
  public/rules_short_ua.pdf
Labels: size/L

#433 Add open_join to tournaments
  app/assets/stylesheets/teams.scss
  app/client/locales/locales.json
  app/controllers/telegram/webhook_controller.rb
  app/helpers/application_helper.rb
  app/models/tournament.rb
  app/views/join_requests/new.html.haml
  config/locales/en.yml
  config/locales/ua.yml
  db/migrate/20240323171835_add_open_join_to_tournaments.rb
  db/schema.rb
Labels: size/L
