Repository yurak/fanta, pull requests merged in 2024-01, with the labels that each got.

#412 Add tm position parser and mapper
  .rubocop_todo.yml
  app/models/player.rb
  app/services/players/tm_parser.rb
  app/services/players/transfermarkt/parser.rb
  app/services/players/transfermarkt/position_mapper.rb
  app/services/players/transfermarkt/position_parser.rb
  lib/tasks/tm/check_club_player_position.rake
  lib/tasks/tm/inject_player_data.rake
  spec/services/players/tm_parser_spec.rb
  spec/services/players/transfermarkt/parser_spec.rb
  spec/services/players/transfermarkt/position_mapper_spec.rb
  spec/services/players/transfermarkt/position_parser_spec.rb
  spec/vcr/player_position_am_cm.yml
  spec/vcr/player_position_am_fw.yml
  spec/vcr/player_position_fw.yml
  spec/vcr/player_position_st_fw.yml
  spec/vcr/player_position_w_am_fw.yml
  spec/vcr/player_position_wb_def.yml
  spec/vcr/player_tm_parser_full.yml
  spec/vcr/player_tm_parser_full_chip.yml
  spec/vcr/player_tm_parser_retired.yml
  spec/vcr/player_without_position.yml
Labels: size/XL

#413 Fix codefactor issues
  app/controllers/lineups_controller.rb
  app/models/league.rb
  app/services/results/national_updater.rb
  lib/tasks/db_updater.rake
  lib/tasks/positions.rake
  lib/tasks/teams.rake
  lib/tasks/tours.rake
  spec/services/auction_rounds/manager_spec.rb
  spec/services/clubs/creator_spec.rb
  spec/services/national_teams/creator_spec.rb
  spec/services/positions/creator_spec.rb
  spec/services/round_players/creator_spec.rb
  spec/services/slots/creator_spec.rb
Labels: size/M

#398 Version 3.2.0
  .rubocop_todo.yml
  app/assets/stylesheets/tournament_rounds.scss
  app/controllers/lineups_controller.rb
  app/controllers/tournament_rounds_controller.rb
  app/models/league.rb
  app/models/lineup.rb
  app/models/player.rb
  app/models/tournament_round.rb
  app/services/lineups/cloner.rb
  app/services/lineups/updater.rb
  app/services/players/tm_parser.rb
  app/services/players/transfermarkt/parser.rb
  app/services/players/transfermarkt/position_mapper.rb
  app/services/players/transfermarkt/position_parser.rb
  app/services/results/national_updater.rb
  app/views/tournament_rounds/edit.html.haml
  db/migrate/20231023150828_add_final_goals_to_lineups.rb
  db/schema.rb
  lib/tasks/db_updater.rake
  lib/tasks/positions.rake
  lib/tasks/teams.rake
  lib/tasks/tm/check_club_player_position.rake
  lib/tasks/tm/inject_player_data.rake
  lib/tasks/tours.rake
  spec/models/lineup_spec.rb
  spec/services/auction_rounds/manager_spec.rb
  spec/services/clubs/creator_spec.rb
  spec/services/lineups/updater_spec.rb
  spec/services/national_teams/creator_spec.rb
  spec/services/players/tm_parser_spec.rb
  spec/services/players/transfermarkt/parser_spec.rb
  spec/services/players/transfermarkt/position_mapper_spec.rb
  spec/services/players/transfermarkt/position_parser_spec.rb
  spec/services/positions/creator_spec.rb
  spec/services/round_players/creator_spec.rb
  spec/services/slots/creator_spec.rb
  spec/vcr/player_position_am_cm.yml
  spec/vcr/player_position_am_fw.yml
  spec/vcr/player_position_fw.yml
  spec/vcr/player_position_st_fw.yml
  spec/vcr/player_position_w_am_fw.yml
  spec/vcr/player_position_wb_def.yml
  spec/vcr/player_tm_parser_full.yml
  spec/vcr/player_tm_parser_full_chip.yml
  spec/vcr/player_tm_parser_retired.yml
  spec/vcr/player_without_position.yml
Labels: size/XL

#416 Configurate eslint
  .eslintrc.json
  app/client/api/query/useLeagues.ts
  app/client/bootstrap/AppProvider.tsx
  app/client/components/PageHeading/PageHeading.tsx
  app/client/components/SeasonsSelect/SeasonsSelect.tsx
  app/client/components/TournamentsTabs/TournamentsTabs.tsx
  app/client/declaration/window.d.ts
  app/client/interfaces/League.ts
  app/client/interfaces/Season.ts
  app/client/interfaces/Tournament.ts
  app/client/interfaces/api/Response.ts
  app/client/pages/Leagues/LeaguesList/LeagueLoader/LeagueLoader.tsx
  app/client/pages/Leagues/LeaguesList/LeaguesList.tsx
  app/client/pages/Leagues/LeaguesList/LeaguesListDesktop/LeaguesListDesktop.tsx
  app/client/pages/Leagues/LeaguesList/LeaguesListMobile/LeaguesListMobile.tsx
  app/client/pages/Leagues/interfaces.ts
  app/client/ui/DataList/DataList.tsx
  app/client/ui/EmptyState/EmptyState.tsx
  app/client/ui/Label/Label.tsx
  app/client/ui/Search/Search.tsx
  app/client/ui/Select/Select.tsx
  app/client/ui/Switcher/Switcher.tsx
  app/client/ui/Table/Table.tsx
  app/client/ui/Tabs/Tabs.tsx
  package.json
  yarn.lock
Labels: size/XXL

#417 Leagues UI issues
  app/client/assets/icons/closeRing.svg
  app/client/pages/Leagues/LeaguesList/LeaguesListDesktop/LeaguesListDesktop.module.scss
  app/client/ui/Search/Search.module.scss
  app/client/ui/Search/Search.tsx
  app/client/ui/Tabs/Tabs.module.scss
Labels: size/M

#418 Add reserve to clubs
  app/models/club.rb
  app/services/players/transfermarkt/parser.rb
  db/migrate/20240113091140_add_reserve_clubs_to_clubs.rb
  db/schema.rb
  lib/tasks/tm/check_player_club_data.rake
Labels: size/M

#419 Add auction sales deadline notifier
  app/services/auctions/manager.rb
  app/services/telegram_bot/auction_sales_ddl_notifier.rb
  app/services/telegram_bot/auction_sales_open_notifier.rb
  config/schedule.rb
  lib/tasks/tg/save_messages.rake
  lib/tasks/tg/send_auction_sales_deadline.rake
  lib/tasks/tg/send_tour_deadline.rake
  spec/services/telegram_bot/auction_sales_ddl_notifier_spec.rb
  spec/services/telegram_bot/auction_sales_open_notifier_spec.rb
Labels: size/L
