Repository yurak/fanta, pull requests merged in 2024-08, with the labels that each got.

#464 Add new relic gem
  Capfile
  Gemfile
  Gemfile.lock
  config/appsignal.yml
Labels: size/M

#467 Rollbar
  Gemfile
  Gemfile.lock
  app/models/configuration.rb
  config/database.yml
  config/initializers/rollbar.rb
  db/migrate/20240812074455_create_configurations.rb
  db/migrate/20240812085805_add_uniq_index.rb
  db/schema.rb
  spec/factories/configurations.rb
Labels: size/L

#466 Update injectors
  app/services/scores/injectors/fotmob_match.rb
  app/services/scores/injectors/fotmob_players_data.rb
  app/services/scores/injectors/sofascore.rb
  app/services/scores/injectors/sofascore_match.rb
Labels: size/S

#468 Update injector
  app/models/configuration.rb
  app/services/scores/injectors/sofascore.rb
  app/services/scores/injectors/sofascore_match.rb
Labels: size/M

#469 Update bonus icons
  app/assets/images/bonuses/assist.png
  app/assets/images/bonuses/assist.svg
  app/assets/images/bonuses/autogol.png
  app/assets/images/bonuses/clean_sheet.svg
  app/assets/images/bonuses/conc_pen.png
  app/assets/images/bonuses/cs.png
  app/assets/images/bonuses/get_in.png
  app/assets/images/bonuses/get_out.png
  app/assets/images/bonuses/goal.png
  app/assets/images/bonuses/goal_missed.svg
  app/assets/images/bonuses/goal_scored.svg
  app/assets/images/bonuses/mg.png
  app/assets/images/bonuses/miss_pen.png
  app/assets/images/bonuses/not_in_squad.png
  app/assets/images/bonuses/own_goal.svg
  app/assets/images/bonuses/pen.png
  app/assets/images/bonuses/penalty_caught.svg
  app/assets/images/bonuses/penalty_earned.svg
  app/assets/images/bonuses/penalty_failed.svg
  app/assets/images/bonuses/penalty_foul.svg
  app/assets/images/bonuses/penalty_missed.svg
  app/assets/images/bonuses/penalty_scored.svg
  app/assets/images/bonuses/position_malus.svg
  app/assets/images/bonuses/rc.png
  app/assets/images/bonuses/red_card.svg
  app/assets/images/bonuses/saves.svg
  app/assets/images/bonuses/won_pen.png
  app/assets/images/bonuses/yc.png
  app/assets/images/bonuses/yellow_card.svg
  app/assets/stylesheets/matches.scss
  app/services/scores/injectors/sofascore_match.rb
  app/services/tours/manager.rb
  app/views/matches/_main_player.html.haml
  app/views/matches/_mp_bonuses.html.haml
  app/views/players/_performance.html.haml
Labels: size/L

#456 Auto subs
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  Gemfile.lock
  app/client/locales/locales.json
  app/controllers/matches_controller.rb
  app/controllers/tournament_rounds_controller.rb
  app/controllers/tours_controller.rb
  app/models/ability.rb
  app/models/league.rb
  app/models/lineup.rb
  app/models/match.rb
  app/models/match_player.rb
  app/models/player.rb
  app/models/substitute.rb
  app/models/tour.rb
  app/services/scores/position_malus/counter.rb
  app/services/substitutes/auto_bot.rb
  app/services/substitutes/creator.rb
  app/views/lineups/show.html.haml
  app/views/matches/_main_player.html.haml
  app/views/matches/_subs_player.html.haml
  app/views/matches/show.html.haml
  app/views/tournament_rounds/auto_subs_preview.html.haml
  app/views/tournament_rounds/show.html.haml
  app/views/tours/preview.html.haml
  config/locales/en.yml
  config/locales/ua.yml
  config/routes.rb
  db/migrate/20240624070922_add_subs_by_to_substitute.rb
  db/migrate/20240712174321_add_substitutesto_lineup.rb
  db/schema.rb
  spec/helpers/players_helper_spec.rb
  spec/models/tour_spec.rb
  spec/services/substitutes/auto_bot_spec.rb
Labels: size/L

#470 Revert "Auto subs"
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  Gemfile.lock
  app/client/locales/locales.json
  app/controllers/matches_controller.rb
  app/controllers/tournament_rounds_controller.rb
  app/controllers/tours_controller.rb
  app/models/ability.rb
  app/models/league.rb
  app/models/lineup.rb
  app/models/match.rb
  app/models/match_player.rb
  app/models/player.rb
  app/models/substitute.rb
  app/models/tour.rb
  app/services/scores/position_malus/counter.rb
  app/services/substitutes/auto_bot.rb
  app/services/substitutes/creator.rb
  app/views/lineups/show.html.haml
  app/views/matches/_main_player.html.haml
  app/views/matches/_subs_player.html.haml
  app/views/matches/show.html.haml
  app/views/tournament_rounds/auto_subs_preview.html.haml
  app/views/tournament_rounds/show.html.haml
  app/views/tours/preview.html.haml
  config/locales/en.yml
  config/locales/ua.yml
  config/routes.rb
  db/migrate/20240624070922_add_subs_by_to_substitute.rb
  db/migrate/20240712174321_add_substitutesto_lineup.rb
  db/schema.rb
  spec/helpers/players_helper_spec.rb
  spec/models/tour_spec.rb
  spec/services/substitutes/auto_bot_spec.rb
Labels: size/L

#471 Auto subs
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  Gemfile.lock
  app/client/locales/locales.json
  app/controllers/matches_controller.rb
  app/controllers/tournament_rounds_controller.rb
  app/controllers/tours_controller.rb
  app/helpers/players_helper.rb
  app/models/ability.rb
  app/models/league.rb
  app/models/lineup.rb
  app/models/match.rb
  app/models/match_player.rb
  app/models/player.rb
  app/models/substitute.rb
  app/models/tour.rb
  app/services/scores/position_malus/counter.rb
  app/services/substitutes/auto_bot.rb
  app/services/substitutes/creator.rb
  app/views/lineups/_lineup_form.html.haml
  app/views/lineups/show.html.haml
  app/views/matches/_main_player.html.haml
  app/views/matches/show.html.haml
  app/views/tournament_rounds/auto_subs_preview.html.haml
  app/views/tournament_rounds/show.html.haml
  app/views/tours/preview.html.haml
  config/locales/en.yml
  config/locales/ua.yml
  config/routes.rb
  db/migrate/20240624070922_add_subs_by_to_substitute.rb
  db/migrate/20240712174321_add_substitutesto_lineup.rb
  db/schema.rb
  spec/helpers/players_helper_spec.rb
  spec/models/tour_spec.rb
  spec/services/substitutes/auto_bot_spec.rb
Labels: size/L
